# Name of website
title: CI-0202 Principios de Informática

# Your name to show in the footer
author: Sivana Hamer

#Theme used
remote_theme: daattali/beautiful-jekyll@5.0.0

#Remove duplicate headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

#Include for Math in HTML
head-extra: head_extra.html