# Name of website
title: CI-0202 Principios de Informática

# Your name to show in the footer
author: Sivana Hamer

#Theme used
theme: beautiful-jekyll-theme

#Remove duplicate headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 


#Colors site
link-col: "#DD003F"
hover-col: "#AEDD00"