# Name of website
title: CI-0202 Principios de Informática

# Your name to show in the footer
author: Sivana Hamer

#Theme used
remote_theme: daattali/beautiful-jekyll@5.0.0

#Remove duplicate headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "ejemplos"
    values:
      layout: "ejemplos"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      ext-js: "https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_CHTML"